version: '2.3'

services:
  bot:
    # github registry
    # image: ghcr.io/gasoid/merge-bot:latest
    # dockerhub registry
    image: gasoid/merge-bot:latest
    restart: always
    volumes:
      - tls-cache:/tmp/tls/.cache
    ports:
      - "443:443"
      - "8080:8080"
    env_file:
      - bot.env
    logging:
      driver: syslog

volumes:
  tls-cache:
